### ISSUE TITLE
Problème de marges pour les boutons

### ISSUE THREAD

**Issue by daviserez** [Ecodev/angular-natural-gallery#10]
Depuis Angular Material 15, il semble que les boutons n'ont plus de marges spécifiées (à 0).

Du coup, je me suis rendu compte que sur dilps-tiresias, tous nos boutons avaient une marge à droite de 5px.

Après quelques recherches, il semble, sauf erreur de ma part, que cela provient de NaturalGallery, plus précisément la clause CSS située dans [ce fichier](https://github.com/Ecodev/angular-natural-gallery/blob/b7c2c2d24a5c8860be1a0999ddcd6fae2700e2d5/projects/angular-natural-gallery/src/lib/natural-gallery/natural-gallery.component.scss) (qui s'applique à un composant non encapsulé).

Je ne pense pas que ce soit le comportement souhaité?

Exemple:
![CleanShot 2023-04-28 at 16 13 38@2x](https://user-images.githubusercontent.com/832658/235171665-acccde12-0a50-4534-bae1-9e7e19a02372.png)

**Comment by sambaptista** [comment]
C'est juste, c'est un résidu qui vient d'être enlevé.
