### ISSUE TITLE
Custom implementation based to add PhotSwipe options

### ISSUE THREAD

**Issue by evenlumi** [Ecodev/angular-natural-gallery#6]
Hi,

I'm trying to implement natural-gallery-js based on this wrapper on my own, so I can customize the PhotoSwipe elements, add my own etc. However, the gallery only shows black images, not the actual previews. The PhotoSwipe however, is working perfectly fine, except it only opens when clicking on the preview title, since there's no image? Do I need to add some style somewhere, or what am I missing?

Thanks, in advance.

![image](https://user-images.githubusercontent.com/57815908/73029650-9e20cc00-3e40-11ea-91d0-8521ce022b93.png)

**Comment by evenlumi** [comment]
Never mind, I just realized options object has a subset of photoSwipeOptions.
Still a little curious though, as to why this may have happened..

**Comment by sambaptista** [comment]
I guess I can close ... ? if I misunderstood, feel free to reopen, and mention what may be pending issue.
